apiVersion: v1
kind: Service
metadata:
  name: spring-eks-demo-service
  labels:
    app: spring-eks-demo
spec:
  type: LoadBalancer
  selector:
    app: spring-eks-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
